# Generated by Django 5.2.15 on 2026-06-26 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_en', models.CharField(blank=True, max_length=200)),
                ('que_es', models.TextField(blank=True)),
                ('para_que', models.TextField(blank=True)),
                ('incluye_texto', models.TextField(blank=True)),
                ('dias_entrega', models.PositiveIntegerField(default=15)),
                ('precio_regular', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('es_destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('nombre_proyecto', models.CharField(max_length=300)),
                ('nombre_proyecto_subtitulo', models.CharField(blank=True, max_length=300)),
                ('dirigido_a', models.CharField(max_length=300)),
                ('empresa_cliente', models.CharField(blank=True, max_length=300)),
                ('de', models.CharField(default='Contexto Arquitectura', max_length=300)),
                ('fecha_presentacion', models.DateField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('objetivo_texto', models.TextField()),
                ('requisitos_texto', models.TextField(blank=True)),
                ('consideraciones_texto', models.TextField(blank=True)),
                ('color_acento', models.CharField(default='#C8A96E', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Propuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='propuestas.paquete')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='propuestas.propuesta'),
        ),
        migrations.CreateModel(
            name='ObjetivoAlineado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, default='star', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='propuestas.propuesta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=300)),
                ('porcentaje', models.PositiveIntegerField()),
                ('fecha_pago', models.CharField(max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='propuestas.propuesta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='propuestas.propuesta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
