# Generated by Django 5.2.15 on 2026-06-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('propuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceptacion', to='propuestas.propuesta')),
            ],
        ),
    ]
