# Generated by Django 5.2.15 on 2026-06-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='aplica_iva',
            field=models.BooleanField(default=False),
        ),
    ]
